name: Docker Image CI

on:
  push:
    branches:
      - master

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Get version
      run: echo ::set-output name=tag::$(node -p -e "require('./package.json').version")
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag acknowledge/gke-test:latest acknowledge/gke-test:${{steps.vars.outputs.tag}}
